Use wrapping_shr in reverse_index_bits_in_place_small
0xPolygonZero/plonky2 pull request #1478
Opened 2024-01-19 06:54 UTC by vivekvpandya

This get triggered when running plonky2 in wasm32-wasi target.

2024-01-19 16:51 UTC, Nashtare approved these changes
Thanks, this looks good to me.
As a matter of curiosity, were you in debug or release mode when encountering the failure in WASM?

Arithmetic operations are _checked_ in `debug` mode, but always switched to _wrapping_ variants in `release` mode, hence why I am a bit confused as to why this would pop up in WASI targets only, unless it actually happened because of the compilation profile.

2024-01-19 18:29 UTC, dlubarov commented
Hm, my understanding is a shift should panic only if debug assertions are enabled (as Robin mentioned) and the shift amount exceeds the size of the integer type, here `usize`.

Here `n_power` should be <= 6 so the shift amount should also be <= 6 so I can't think of why this would trigger. Do you have the stack trace handy?

2024-01-20 11:03 UTC, vivekvpandya commented
> Hm, my understanding is a shift should panic only if debug assertions are enabled (as Robin mentioned) and the shift amount exceeds the size of the integer type, here `usize`.
> 
> Here `n_power` should be <= 6 so the shift amount should also be <= 6 so I can't think of why this would trigger. Do you have the stack trace handy?

```bash
thread 'main' panicked at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/util/src/lib.rs:128:26:
attempt to shift right with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to run main module `../target/wasm32-wasi/debug/demo.wasm`
Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x16817a - panic_abort::__rust_start_panic::abort::h7e5f56383e5819e3
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/panic_abort/src/lib.rs:96:17              - __rust_start_panic
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/panic_abort/src/lib.rs:38:5              - rust_panic
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:831:25
           1: 0x1680c7 - std::panicking::rust_panic_with_hook::hdf66bc2f41fd5166
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:801:5
           2: 0x166ec4 - std::panicking::begin_panic_handler::{{closure}}::h8bd2da1b57ff8909
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:649:13
           3: 0x166e2a - std::sys_common::backtrace::__rust_end_short_backtrace::h4a1d4fa30b25df94
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:171:18
           4: 0x167ad6 - rust_begin_unwind
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:645:5
           5: 0x9267 - core::panicking::panic_fmt::h919872f6efaee18c
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panicking.rs:72:14
           6: 0x6a0f - core::panicking::panic::hcdbcff129c6a1e40
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panicking.rs:144:5
           7: 0x383b8 - plonky2_util::reverse_index_bits_in_place_small::h569ac8c80c4d65f2
                           at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/util/src/lib.rs:128:26              - plonky2_util::reverse_index_bits_in_place::hf0d5b3c3086d43b9
                           at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/util/src/lib.rs:191:13
           8: 0xed8f6 - plonky2_field::fft::fft_classic::h4d45851f19dbc28b
                           at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/field/src/fft.rs:170:5
           9: 0xefd61 - plonky2_field::fft::fft_dispatch::h6e60a467b6abc9c9
                           at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/field/src/fft.rs:48:5              - plonky2_field::fft::ifft_with_options::h09c6f8abe78d5779
                           at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/field/src/fft.rs:82:5
          10: 0xb589b - plonky2_field::fft::ifft::h8ed37c276c8d21e6
                           at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/field/src/fft.rs:69:5              - plonky2_field::polynomial::PolynomialValues<F>::ifft::h6e040a4c1fac48a2
                           at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/field/src/polynomial/mod.rs:59:9              - plonky2::fri::oracle::PolynomialBatch<F,C,_>::from_values::{{closure}}::hc55194f082157538
                           at /Users/jakub/.cargo/git/checkouts/plonky2-fb94951b5f6820ea/70d88e2/plonky2/src/fri/oracle.rs:68:46              - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h16d26ad46affd808
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/ops/function.rs:272:13              - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h3f929a8c30226b29
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/ops/function.rs:305:13              - core::option::Option<T>::map::hfc29c9aee87449a5
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/option.rs:1072:29              - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h7fe590a6a56574aa
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/iter/adapters/map.rs:104:26              - rayon::iter::plumbing::Folder::consume_iter::h1991e62f59310962
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:178:21
          11: 0x20f09 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h5ba1030fedd68df5
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/map.rs:248:21              - rayon::iter::plumbing::Producer::fold_with::h8d0423210c6c1625
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:110:9              - rayon::iter::plumbing::bridge_producer_consumer::helper::he5697d8657a46f83
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:438:13
          12: 0x866f6 - rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::heee6db58d11e9c7e
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:418:21              - rayon_core::join::join_context::call_a::{{closure}}::h179b02a593e9573a
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/join/mod.rs:124:17              - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h510279509437bc63
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panic/unwind_safe.rs:272:9              - std::panicking::try::do_call::hbb7f61e1923255ed
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:552:40              - std::panicking::try::h10242cfb9cbb5cf6
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:516:19              - std::panic::catch_unwind::h67b3bc45d9e779cf
                           at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panic.rs:142:14              - rayon_core::unwind::halt_unwinding::h8a6b1e813c61e0bf
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/unwind.rs:17:5              - rayon_core::join::join_context::{{closure}}::hea5da6f22b0b8228
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/join/mod.rs:142:24
          13: 0x20dd3 - rayon_core::registry::in_worker::h39d5e28468f90566
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:950:13              - rayon_core::join::join_context::h8b0e74165c926923
                           at /Users/jakub/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/join/mod.rs:132:5              - rayon::iter::plumbing::bridge_producer_consumer::helper::he5697d8657a46f83
                          [...]

2024-01-21 00:23 UTC, dlubarov commented
Thanks, I was looking at the wrong shift, here looks like the shift amount is

```rust
let dst_lo_shr_amt = 64 - (lb_n - 6);
```

Seems it was written with the assumption that `usize` would be 64 bits, but for wasm it's probably 32? Should we replace `64` with `size_of::<usize>() * 8`? @nbgl

2024-01-22 13:38 UTC, Nashtare commented
> Should we replace 64 with size_of::<usize>() * 8?

Don't we have other places where `usize` is assumed to be 64-bit long? At least on the evm crate it is I believe.

2024-01-25 05:57 UTC, vivekvpandya commented
> Thanks, I was looking at the wrong shift, here looks like the shift amount is
> 
> ```rust
> let dst_lo_shr_amt = 64 - (lb_n - 6);
> ```
> 
> Seems it was written with the assumption that `usize` would be 64 bits, but for wasm it's probably 32? Should we replace `64` with `size_of::<usize>() * 8`? @nbgl

@Nashtare should we go with this suggestion? what else needs to be done to merge this PR?

2024-01-25 13:13 UTC, Nashtare commented
Yeah I'd rather go with this suggestion instead.

2024-01-25 14:49 UTC, Nashtare requested changes

2024-01-25 14:49 UTC, Nashtare commented on util/src/lib.rs
> +        let dst_shr_amt = usize::BITS - lb_n as u32;
This change is incorrect, we should keep `6 - lb_n` here.

2024-01-26 04:55 UTC, vivekvpandya commented
@Nashtare kindly review!

2024-01-26 15:10 UTC, Nashtare approved these changes

2024-01-26 15:10 UTC, merged